import type { Product, Category, Rarity } from "@shared/schema";

export const rarityColors: Record<string, string> = {
  Common: "bg-gray-500/10 text-gray-500",
  Uncommon: "bg-green-500/10 text-green-500",
  Rare: "bg-blue-500/10 text-blue-500",
  Legendary: "bg-purple-500/10 text-purple-500",
  Godly: "bg-orange-500/10 text-orange-500",
  Ancient: "bg-red-500/10 text-red-500",
  Chroma: "bg-gradient-to-r from-pink-500/20 to-purple-500/20 text-pink-500",
};

export const categoryInfo: Record<string, { description: string; itemCount: number }> = {
  Budget: { description: "Affordable items for beginners", itemCount: 0 },
  Standard: { description: "Popular items with great value", itemCount: 0 },
  Godly: { description: "Rare and powerful godly items", itemCount: 0 },
  Ancient: { description: "Legendary ancient artifacts", itemCount: 0 },
  Bundles: { description: "Value bundles and sets", itemCount: 0 },
  Royal: { description: "Premium exclusive collections", itemCount: 0 },
};

function generateId(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-');
}

const productImages: Record<string, string> = {
  "2015": "/products/2015-commons-899_500x500.webp.png",
  "8-bit-bundle": "/products/8-bit-bundle-godlies-441_500x500.webp.png",
  "america-bundle": "/products/america-bundle-godlies-449_500x500.webp.png",
  "amerilaser": "/products/amerilaser-godlies-318_500x500.webp.png",
  "ancient-mega-bundle": "/products/ancient-mega-bundle-ancients-526_500x500.webp.png",
  "aurora-set": "/products/aurora-set-commons-882_500x500.webp.png",
  "badger": "/products/badger-commons-226_500x500.webp.png",
  "bat-bundle": "/products/bat-bundle-legendaries-643_500x500.webp.png",
  "bat": "/products/bat-godlies-929_500x500.webp.png",
  "battleaxe-ii": "/products/battleaxe-ii-godlies-917_500x500.webp.png",
  "battleaxe-set": "/products/battleaxe-set-ancients-115_500x500.webp.png",
  "battleaxe": "/products/battleaxe-ii-godlies-917_500x500.webp.png",
  "batwing": "/products/batwing-ancients-111_500x500.webp.png",
  "bauble": "/products/bauble-godlies-220_500x500.webp.png",
  "bioblade": "/products/bioblade-godlies-705_500x500.webp.png",
  "blood": "/products/blood-vintages-231_500x500.webp.png",
  "bloom-set": "/products/bloom-set-godlies-175_500x500.webp.png",
  "blossom": "/products/blossom-commons-100_500x500.webp.png",
  "blue-elite": "/products/blue-elite-legendaries-299_500x500.webp.png",
  "blue-scratch": "/products/blue-scratch-legendaries-541_500x500.webp.png",
  "blue-seer": "/products/blue-seer-godlies-852_500x500.webp.png",
  "boneblade": "/products/boneblade-godlies-838_500x500.webp.png",
  "borealis": "/products/borealis-godlies-277_500x500.webp.png",
  "borealis-set": "/products/borealis-set-godlies-222_500x500.webp.png",
  "box-of-fert": "/products/box-of-fert-commons-895_500x500.webp.png",
  "box-of-ultra-wrapping-paper": "/products/box-of-ultra-wrapping-paper-commons-297_500x500.webp.png",
  "bringer-set": "/products/bringer-set-godlies-944_500x500.webp.png",
  "candleflame": "/products/candleflame-godlies-541_500x500.webp.png",
  "candy": "/products/candy-godlies-518_500x500.webp.png",
  "candy-set": "/products/candy-set-godlies-947_500x500.webp.png",
  "cane-gun": "/products/cane-gun-rares-998_500x500.webp.png",
  "cane-knife": "/products/cane-knife-rares-921_500x500.webp.png",
  "cavern-gun": "/products/cavern-gun-legendaries-476_500x500.webp.png",
  "cavern-knife": "/products/cavern-knife-legendaries-176_500x500.webp.png",
  "celestial": "/products/celestial-ancients-913_500x500.webp.png",
  "chill": "/products/chill-godlies-937_500x500.webp.png",
  "chilly": "/products/chilly-uncommons-469_500x500.webp.png",
  "christmas-collection": "/products/christmas-collection-godlies-936_500x500.webp.png",
  "chroma-bringer-set": "/products/chroma-bringer-set-chromas-488_500x500.webp.png",
  "chroma-candleflame": "/products/chroma-candleflame-chromas-171_500x500.webp.png",
  "chroma-cookiecane": "/products/chroma-cookiecane-chromas-603_500x500.webp.png",
  "chroma-darkbringer": "/products/chroma-darkbringer-chromas-362_500x500.webp.png",
  "chroma-deathshard": "/products/chroma-deathshard-chromas-199_500x500.webp.png",
  "chroma-elderwood-blade": "/products/chroma-elderwood-blade-chromas-552_500x500.webp.png",
  "chroma-fire-bunny": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "chroma-fire-cat": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "chroma-fire-dog": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "chroma-fire-fox": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "chroma-fire-pig": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "chroma-fire-bear": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "chroma-fire-bat": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "chroma-fire-pets-set": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "chroma-gemstone": "/products/chroma-gemstone-chromas-567_500x500.webp.png",
  "chroma-gingerblade": "/products/chroma-gingerblade-chromas-728_500x500.webp.png",
  "chroma-gun-set": "/products/chroma-gun-set-chromas-707_500x500.webp.png",
  "chroma-heat": "/products/chroma-heat-chromas-906_500x500.webp.png",
  "chroma-knife-set-2": "/products/chroma-knife-set-2-chromas-832_500x500.webp.png",
  "chroma-knife-set": "/products/chroma-knife-set-chromas-661_500x500.webp.png",
  "chroma-laser": "/products/chroma-laser-chromas-365_500x500.webp.png",
  "chroma-lightbringer": "/products/chroma-lightbringer-chromas-827_500x500.webp.png",
  "chroma-luger": "/products/chroma-luger-chromas-194_500x500.webp.png",
  "chroma-saw": "/products/chroma-saw-chromas-425_500x500.webp.png",
  "chroma-seer": "/products/chroma-seer-chromas-832_500x500.webp.png",
  "chroma-shark": "/products/chroma-shark-chromas-323_500x500.webp.png",
  "chroma-swirly-gun": "/products/chroma-swirly-gun-chromas-974_500x500.webp.png",
  "clockwork": "/products/clockwork-godlies-668_500x500.webp.png",
  "constellation": "/products/constellation-godlies-926_500x500.webp.png",
  "cookie-bundle": "/products/cookie-bundle-godlies-715_500x500.webp.png",
  "cookiecane": "/products/cookiecane-godlies-734_500x500.webp.png",
  "corrupt": "/products/corrupt-uniques-124_500x500.webp.png",
  "cotton-candy": "/products/cotton-candy-legendaries-560_500x500.webp.png",
  "darkbringer": "/products/darkbringer-godlies-178_500x500.webp.png",
  "dark-bundle": "/products/dark-bundle-godlies-363_500x500.webp.png",
  "darkshot": "/products/darkshot-godlies-821_500x500.webp.png",
  "darksword": "/products/darksword-godlies-648_500x500.webp.png",
  "deathshard": "/products/deathshard-godlies-931_500x500.webp.png",
  "deathspeaker": "/products/deathspeaker-godlies-182_500x500.webp.png",
  "easter-bundle": "/products/easter-bundle-commons-299_500x500.webp.png",
  "elderwood-blade": "/products/elderwood-blade-godlies-898_500x500.webp.png",
  "elderwood-revolver": "/products/elderwood-revolver-godlies-184_500x500.webp.png",
  "elderwood-scythe": "/products/elderwood-scythe-godlies-250_500x500.webp.png",
  "elderwood-set": "/products/elderwood-set-ancients-627_500x500.webp.png",
  "elf-knife": "/products/elf-knife-commons-376_500x500.webp.png",
  "elite": "/products/elite-legendaries-567_500x500.webp.png",
  "eternalcane": "/products/eternalcane-godlies-546_500x500.webp.png",
  "eternalcane-set": "/products/eternalcane-set-godlies-167_500x500.webp.png",
  "eternal-iii": "/products/eternal-iii-godlies-908_500x500.webp.png",
  "eternal-ii": "/products/eternal-ii-godlies-534_500x500.webp.png",
  "eternal-iv": "/products/eternal-iv-godlies-669_500x500.webp.png",
  "eternal": "/products/eternal-godlies-902_500x500.webp.png",
  "eternal-set": "/products/eternal-set-godlies-719_500x500.webp.png",
  "ever-bundle": "/products/ever-bundle-godlies-457_500x500.webp.png",
  "evergreen": "/products/evergreen-godlies-137_500x500.webp.png",
  "evergun": "/products/evergun-godlies-789_500x500.webp.png",
  "eyeball": "/products/eyeball-rares-119_500x500.webp.png",
  "fairy": "/products/fairy-uncommons-634_500x500.webp.png",
  "fang": "/products/fang-godlies-268_500x500.webp.png",
  "flames": "/products/flames-godlies-691_500x500.webp.png",
  "flora": "/products/flora-godlies-459_500x500.webp.png",
  "flowerwood-set": "/products/flowerwood-set-godlies-221_500x500.webp.png",
  "frostbite": "/products/frostbite-godlies-356_500x500.webp.png",
  "frostbird": "/products/frostbite-godlies-356_500x500.webp.png",
  "frostsaber": "/products/frostsaber-godlies-484_500x500.webp.png",
  "full-elderwood-bundle": "/products/full-elderwood-bundle-ancients-155_500x500.webp.png",
  "full-ice-bundle": "/products/full-ice-bundle-godlies-349_500x500.webp.png",
  "full-swirly-bundle": "/products/full-swirly-bundle-godlies-100_500x500.webp.png",
  "futuristic-pack": "/products/futuristic-pack-godlies-355_500x500.webp.png",
  "gemstone": "/products/gemstone-godlies-960_500x500.webp.png",
  "ghost": "/products/ghost-vintages-587_500x500.webp.png",
  "gingerblade": "/products/gingerblade-godlies-849_500x500.webp.png",
  "ginger-gun": "/products/ginger-gun-rares-330_500x500.webp.png",
  "ginger-luger": "/products/ginger-luger-godlies-998_500x500.webp.png",
  "gingermint": "/products/gingermint-godlies-928_500x500.webp.png",
  "gingerscope": "/products/gingerscope-ancients-670_500x500.webp.png",
  "glitch-knife": "/products/glitch-knife-commons-451_500x500.webp.png",
  "golden-bundle": "/products/golden-bundle-uniques-594_500x500.webp.png",
  "goo": "/products/goo-commons-952_500x500.webp.png",
  "green-elite": "/products/green-elite-legendaries-373_500x500.webp.png",
  "green-fire": "/products/green-fire-legendaries-892_500x500.webp.png",
  "green-luger": "/products/green-luger-godlies-224_500x500.webp.png",
  "green-marble": "/products/green-marble-rares-884_500x500.webp.png",
  "hallow-bundle": "/products/hallow-bundle-ancients-692_500x500.webp.png",
  "halloween-bundle": "/products/halloween-bundle-ancients-535_500x500.webp.png",
  "hallowgun": "/products/hallowgun-godlies-770_500x500.webp.png",
  "hallows-blade": "/products/hallows-blade-godlies-348_500x500.webp.png",
  "hallowscythe": "/products/hallowscythe-ancients-977_500x500.webp.png",
  "hallows-edge": "/products/hallows-edge-godlies-686_500x500.webp.png",
  "hallow-set": "/products/hallow-set-ancients-152_500x500.webp.png",
  "handsaw": "/products/handsaw-godlies-290_500x500.webp.png",
  "harvester-bundle": "/products/harvester-bundle-godlies-879_500x500.webp.png",
  "harvester": "/products/harvester-ancients-884_500x500.webp.png",
  "heartblade": "/products/heartblade-godlies-347_500x500.webp.png",
  "heart-pet": "/products/heart-pet-commons-797_500x500.webp.png",
  "heat": "/products/heat-godlies-740_500x500.webp.png",
  "icebeam": "/products/icebeam-godlies-477_500x500.webp.png",
  "icebeam-set": "/products/icebeam-set-godlies-615_500x500.webp.png",
  "iceblaster": "/products/iceblaster-godlies-396_500x500.webp.png",
  "icebreaker": "/products/icebreaker-godlies-280_500x500.webp.png",
  "ice-bundle": "/products/ice-bundle-godlies-933_500x500.webp.png",
  "ice-flake": "/products/ice-flake-godlies-359_500x500.webp.png",
  "icepiercer": "/products/icepiercer-ancients-671_500x500.webp.png",
  "ice-shard": "/products/ice-flake-godlies-359_500x500.webp.png",
  "icewing": "/products/icewing-ancients-871_500x500.webp.png",
  "icey": "/products/icey-godlies-802_500x500.webp.png",
  "infected": "/products/infected-commons-303_500x500.webp.png",
  "jd-cotton-candy-bundle": "/products/jd-cotton-candy-bundle-uniques-309_500x500.webp.png",
  "jd": "/products/jd-legendaries-968_500x500.webp.png",
  "jetstream": "/products/jetstream-rares-178_500x500.webp.png",
  "jinglegun": "/products/jinglegun-godlies-952_500x500.webp.png",
  "laser": "/products/laser-godlies-694_500x500.webp.png",
  "lightbringer": "/products/lightbringer-godlies-558_500x500.webp.png",
  "logchopper": "/products/logchopper-ancients-765_500x500.webp.png",
  "lugercane": "/products/lugercane-godlies-578_500x500.webp.png",
  "luger": "/products/luger-godlies-872_500x500.webp.png",
  "makeshift": "/products/makeshift-godlies-452_500x500.webp.png",
  "mechbug": "/products/mechbug-rares-193_500x500.webp.png",
  "mega-chroma-bundle": "/products/mega-chroma-bundle-chromas-256_500x500.webp.png",
  "mega-chroma-knives-bundle": "/products/mega-chroma-knives-bundle-chromas-872_500x500.webp.png",
  "mega-op-bundle": "/products/mega-op-bundle-godlies-797_500x500.webp.png",
  "mega-pet-bundle": "/products/mega-pet-bundle-godlies-294_500x500.webp.png",
  "minty": "/products/minty-godlies-358_500x500.webp.png",
  "miscellaneous-collectible-bundle": "/products/miscellaneous-collectible-bundle-commons-546_500x500.webp.png",
  "mystery-key": "/products/mystery-key-commons-500_500x500.webp.png",
  "nebula": "/products/nebula-godlies-938_500x500.webp.png",
  "nightblade": "/products/nightblade-godlies-828_500x500.webp.png",
  "nobledragon": "/products/nobledragon-legendaries-469_500x500.webp.png",
  "ocean-bundle": "/products/ocean-bundle-uniques-502_500x500.webp.png",
  "ocean": "/products/ocean-godlies-486_500x500.webp.png",
  "old-glory": "/products/old-glory-godlies-673_500x500.webp.png",
  "ornament2-gun": "/products/ornament2-gun-commons-125_500x500.webp.png",
  "ornament2-set": "/products/ornament2-set-commons-598_500x500.webp.png",
  "ornament-gun": "/products/ornament-gun-commons-998_500x500.webp.png",
  "ornament-knife": "/products/ornament-knife-commons-931_500x500.webp.png",
  "overseer-eye": "/products/overseer-eye-legendaries-472_500x500.webp.png",
  "painted-seer-bundle": "/products/painted-seer-bundle-godlies-417_500x500.webp.png",
  "patrick": "/products/patrick-commons-345_500x500.webp.png",
  "pearl-set": "/products/pearl-set-godlies-892_500x500.webp.png",
  "pearlshine": "/products/pearlshine-godlies-617_500x500.webp.png",
  "pengy": "/products/pengy-commons-106_500x500.webp.png",
  "peppermint": "/products/peppermint-godlies-111_500x500.webp.png",
  "phoenix": "/products/phoenix-godlies-868_500x500.webp.png",
  "pixel": "/products/pixel-godlies-637_500x500.webp.png",
  "plasmabeam": "/products/plasmabeam-godlies-444_500x500.webp.png",
  "plasma-bundle": "/products/plasma-bundle-godlies-868_500x500.webp.png",
  "prince": "/products/prince-vintages-220_500x500.webp.png",
  "prismatic": "/products/prismatic-godlies-618_500x500.webp.png",
  "pumpking": "/products/pumpking-godlies-606_500x500.webp.png",
  "red-scratch": "/products/red-scratch-legendaries-678_500x500.webp.png",
  "red-seer": "/products/red-seer-godlies-733_500x500.webp.png",
  "reindeer": "/products/reindeer-commons-131_500x500.webp.png",
  "ripper-knife": "/products/ripper-knife-legendaries-551_500x500.webp.png",
  "rudolph": "/products/rudolph-commons-135_500x500.webp.png",
  "rupture": "/products/rupture-legendaries-108_500x500.webp.png",
  "sammy": "/products/sammy-godlies-556_500x500.webp.png",
  "santa-gun": "/products/santa-gun-commons-227_500x500.webp.png",
  "santa-knife": "/products/santa-knife-commons-178_500x500.webp.png",
  "santas-magic": "/products/santas-magic-legendaries-332_500x500.webp.png",
  "saw": "/products/saw-godlies-561_500x500.webp.png",
  "scarecrow": "/products/scarecrow-rares-292_500x500.webp.png",
  "scythe-set": "/products/scythe-set-ancients-836_500x500.webp.png",
  "seahorsey": "/products/seahorsey-uncommons-387_500x500.webp.png",
  "seer": "/products/seer-godlies-457_500x500.webp.png",
  "shadow": "/products/shadow-vintages-821_500x500.webp.png",
  "shark": "/products/shark-godlies-878_500x500.webp.png",
  "skate-pack": "/products/skate-pack-commons-219_500x500.webp.png",
  "skeleton-key": "/products/skeleton-key-commons-409_500x500.webp.png",
  "skelly": "/products/skelly-godlies-118_500x500.webp.png",
  "skool": "/products/skool-commons-384_500x500.webp.png",
  "slasher": "/products/slasher-godlies-511_500x500.webp.png",
  "small-set": "/products/small-set-2-godlies-979_500x500.webp.png",
  "snowflake-key": "/products/snowflake-key-commons-805_500x500.webp.png",
  "snowflake": "/products/snowflake-godlies-816_500x500.webp.png",
  "soul": "/products/soul-godlies-884_500x500.webp.png",
  "sparkle-10": "/products/sparkle-10-commons-140_500x500.webp.png",
  "sparkle-set": "/products/sparkle-set-commons-330_500x500.webp.png",
  "spectre": "/products/spectre-bundle-320_500x500.webp.png",
  "spider": "/products/spider-godlies-398_500x500.webp.png",
  "spirit-set": "/products/spirit-set-godlies-978_500x500.webp.png",
  "steambird": "/products/steambird-godlies-797_500x500.webp.png",
  "sugar": "/products/sugar-godlies-190_500x500.webp.png",
  "sunrise": "/products/sunrise-godlies-820_500x500.webp.png",
  "sunset": "/products/sunset-godlies-372_500x500.webp.png",
  "sunset-set": "/products/sunset-set-godlies-209_500x500.webp.png",
  "super-luger-bundle": "/products/super-luger-bundle-godlies-318_500x500.webp.png",
  "swirly-blade": "/products/swirly-blade-godlies-517_500x500.webp.png",
  "swirly-gun": "/products/swirly-gun-godlies-945_500x500.webp.png",
  "tides": "/products/tides-godlies-963_500x500.webp.png",
  "tnl": "/products/tnl-commons-519_500x500.webp.png",
  "toxic-set": "/products/toxic-set-commons-855_500x500.webp.png",
  "traveller": "/products/traveller-godlies-307_500x500.webp.png",
  "tree-gun": "/products/tree-gun-legendaries-607_500x500.webp.png",
  "tree-knife": "/products/tree-knife-legendaries-132_500x500.webp.png",
  "turkey-knife": "/products/turkey-knife-godlies-629_500x500.webp.png",
  "ufo": "/products/ufo-commons-211_500x500.webp.png",
  "valentine-bundle": "/products/valentine-bundle-commons-974_500x500.webp.png",
  "vampire-bat": "/products/vampire-bat-legendaries-986_500x500.webp.png",
  "vampire": "/products/vampire-legendaries-171_500x500.webp.png",
  "vampires-axe": "/products/vampires-axe-ancients-308_500x500.webp.png",
  "vampires-edge": "/products/vampires-edge-godlies-398_500x500.webp.png",
  "vampire-set": "/products/vampire-set-uniques-921_500x500.webp.png",
  "vampires-gun": "/products/vampires-gun-godlies-964_500x500.webp.png",
  "vintage-bundle": "/products/vintage-bundle-vintages-864_500x500.webp.png",
  "virtual": "/products/virtual-godlies-577_500x500.webp.png",
  "watergun": "/products/watergun-godlies-101_500x500.webp.png",
  "waves": "/products/waves-godlies-774_500x500.webp.png",
  "web": "/products/web-legendaries-254_500x500.webp.png",
  "winter-bundle": "/products/winter-bundle-godlies-823_500x500.webp.png",
  "winters-edge": "/products/winters-edge-godlies-255_500x500.webp.png",
  "wrapping-paper-bundle": "/products/wrapping-paper-bundle-commons-139_500x500.webp.png",
  "xmas-gifts": "/products/xmas-gifts-commons-271_500x500.webp.png",
  "xmas": "/products/xmas-godlies-125_500x500.webp.png",
  "fire-dog": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "fire-cat": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "fire-bunny": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "fire-pig": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "fire-fox": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "best-bundle": "/products/best-bundle-446_400x400.webp_1.png",
  "brontosaurus": "/products/brontosaurus-193_400x400.webp.png",
};

function getProductImage(name: string): string | null {
  const key = name.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  return productImages[key] || null;
}

export const allProducts: Product[] = [
  { id: generateId("Blue Elite"), name: "Blue Elite", price: 17, category: "Budget", rarity: "Common", description: "A sleek blue elite knife with sharp edges.", inStock: 1, imageUrl: getProductImage("Blue Elite") },
  { id: generateId("Green Elite"), name: "Green Elite", price: 17, category: "Budget", rarity: "Common", description: "A vibrant green elite knife.", inStock: 1, imageUrl: getProductImage("Green Elite") },
  { id: generateId("Skool"), name: "Skool", price: 17, category: "Budget", rarity: "Common", description: "Classic school-themed knife design.", inStock: 1, imageUrl: getProductImage("Skool") },
  { id: generateId("Blossom"), name: "Blossom", price: 17, category: "Budget", rarity: "Common", description: "Beautiful floral blossom knife.", inStock: 1, imageUrl: getProductImage("Blossom") },
  { id: generateId("Hallows Blade"), name: "Hallows Blade", price: 17, category: "Budget", rarity: "Uncommon", description: "Spooky Halloween-themed blade.", inStock: 1, imageUrl: getProductImage("Hallows Blade") },
  { id: generateId("Ornament2 Gun"), name: "Ornament2 Gun", price: 17, category: "Budget", rarity: "Common", description: "Festive ornament-styled gun.", inStock: 1, imageUrl: getProductImage("Ornament2 Gun") },
  { id: generateId("Santa Gun"), name: "Santa Gun", price: 17, category: "Budget", rarity: "Uncommon", description: "Christmas Santa-themed gun.", inStock: 1, imageUrl: getProductImage("Santa Gun") },
  { id: generateId("Ginger Gun"), name: "Ginger Gun", price: 17, category: "Budget", rarity: "Common", description: "Sweet gingerbread gun design.", inStock: 1, imageUrl: getProductImage("Ginger Gun") },
  { id: generateId("Rupture"), name: "Rupture", price: 17, category: "Budget", rarity: "Uncommon", description: "Powerful rupture effect gun.", inStock: 1, imageUrl: getProductImage("Rupture") },
  { id: generateId("Tree Gun"), name: "Tree Gun", price: 17, category: "Budget", rarity: "Common", description: "Nature-themed tree gun.", inStock: 1, imageUrl: getProductImage("Tree Gun") },
  { id: generateId("Ornament Gun"), name: "Ornament Gun", price: 17, category: "Budget", rarity: "Common", description: "Classic ornament gun design.", inStock: 1, imageUrl: getProductImage("Ornament Gun") },
  { id: generateId("Cavern Gun"), name: "Cavern Gun", price: 17, category: "Budget", rarity: "Uncommon", description: "Dark cavern-styled gun.", inStock: 1, imageUrl: getProductImage("Cavern Gun") },
  { id: generateId("Xmas Gifts"), name: "Xmas Gifts", price: 17, category: "Budget", rarity: "Common", description: "Festive Christmas gifts bundle.", inStock: 1, imageUrl: getProductImage("Xmas Gifts") },
  { id: generateId("Pengy"), name: "Pengy", price: 17, category: "Budget", rarity: "Common", description: "Adorable penguin pet.", inStock: 1, imageUrl: getProductImage("Pengy") },
  { id: generateId("UFO"), name: "UFO", price: 17, category: "Budget", rarity: "Rare", description: "Mysterious UFO pet.", inStock: 1, imageUrl: getProductImage("UFO") },
  { id: generateId("Rudolph"), name: "Rudolph", price: 17, category: "Budget", rarity: "Common", description: "Classic Rudolph reindeer pet.", inStock: 1, imageUrl: getProductImage("Rudolph") },
  { id: generateId("Reindeer"), name: "Reindeer", price: 17, category: "Budget", rarity: "Common", description: "Festive reindeer pet.", inStock: 1, imageUrl: getProductImage("Reindeer") },
  { id: generateId("Chilly"), name: "Chilly", price: 17, category: "Budget", rarity: "Common", description: "Cool icy chilly pet.", inStock: 1, imageUrl: getProductImage("Chilly") },
  { id: generateId("Mystery Key"), name: "Mystery Key", price: 17, category: "Budget", rarity: "Rare", description: "Unlock mysterious rewards.", inStock: 1, imageUrl: getProductImage("Mystery Key") },
  { id: generateId("Box Of Fert"), name: "Box Of Fert", price: 17, category: "Budget", rarity: "Common", description: "Special fertilizer box.", inStock: 1, imageUrl: getProductImage("Box Of Fert") },
  { id: generateId("Scarecrow"), name: "Scarecrow", price: 17, category: "Budget", rarity: "Uncommon", description: "Spooky scarecrow pet.", inStock: 1, imageUrl: getProductImage("Scarecrow") },
  { id: generateId("Mechbug"), name: "Mechbug", price: 17, category: "Budget", rarity: "Rare", description: "Mechanical bug pet.", inStock: 1, imageUrl: getProductImage("Mechbug") },
  { id: generateId("Vampire Bat"), name: "Vampire Bat", price: 17, category: "Budget", rarity: "Uncommon", description: "Dark vampire bat pet.", inStock: 1, imageUrl: getProductImage("Vampire Bat") },
  { id: generateId("Seahorsey"), name: "Seahorsey", price: 17, category: "Budget", rarity: "Common", description: "Cute seahorse pet.", inStock: 1, imageUrl: getProductImage("Seahorsey") },
  { id: generateId("Skelly"), name: "Skelly", price: 17, category: "Budget", rarity: "Uncommon", description: "Skeleton-themed pet.", inStock: 1, imageUrl: getProductImage("Skelly") },
  { id: generateId("Skeleton Key"), name: "Skeleton Key", price: 17, category: "Budget", rarity: "Rare", description: "Rare skeleton key item.", inStock: 1, imageUrl: getProductImage("Skeleton Key") },
  { id: generateId("Fairy"), name: "Fairy", price: 17, category: "Budget", rarity: "Rare", description: "Magical fairy pet.", inStock: 1, imageUrl: getProductImage("Fairy") },
  { id: generateId("Traveller"), name: "Traveller", price: 17, category: "Budget", rarity: "Uncommon", description: "Adventure traveller pet.", inStock: 1, imageUrl: getProductImage("Traveller") },
  { id: generateId("Snowflake Key"), name: "Snowflake Key", price: 17, category: "Budget", rarity: "Rare", description: "Icy snowflake key.", inStock: 1, imageUrl: getProductImage("Snowflake Key") },
  { id: generateId("Badger"), name: "Badger", price: 17, category: "Budget", rarity: "Common", description: "Cute badger pet.", inStock: 1, imageUrl: getProductImage("Badger") },
  { id: generateId("Box of Ultra Wrapping Paper"), name: "Box of Ultra Wrapping Paper", price: 17, category: "Budget", rarity: "Common", description: "Ultra quality wrapping paper.", inStock: 1, imageUrl: getProductImage("Box of Ultra Wrapping Paper") },
  { id: generateId("Box of Green Wrapping Paper"), name: "Box of Green Wrapping Paper", price: 17, category: "Budget", rarity: "Common", description: "Green wrapping paper box.", inStock: 1, imageUrl: null },
  { id: generateId("Box of Red Wrapping Paper"), name: "Box of Red Wrapping Paper", price: 17, category: "Budget", rarity: "Common", description: "Red wrapping paper box.", inStock: 1, imageUrl: null },
  { id: generateId("Fire Dog"), name: "Fire Dog", price: 17, category: "Budget", rarity: "Rare", description: "Fiery dog pet with flames.", inStock: 1, imageUrl: getProductImage("Fire Dog") },
  { id: generateId("Fire Cat"), name: "Fire Cat", price: 17, category: "Budget", rarity: "Rare", description: "Blazing fire cat pet.", inStock: 1, imageUrl: getProductImage("Fire Cat") },
  { id: generateId("Fire Bunny"), name: "Fire Bunny", price: 17, category: "Budget", rarity: "Rare", description: "Flaming bunny pet.", inStock: 1, imageUrl: getProductImage("Fire Bunny") },
  { id: generateId("Fire Pig"), name: "Fire Pig", price: 17, category: "Budget", rarity: "Rare", description: "Hot fire pig pet.", inStock: 1, imageUrl: getProductImage("Fire Pig") },
  { id: generateId("Fire Fox"), name: "Fire Fox", price: 17, category: "Budget", rarity: "Rare", description: "Burning fire fox pet.", inStock: 1, imageUrl: getProductImage("Fire Fox") },
  { id: generateId("Blue Scratch"), name: "Blue Scratch", price: 17, category: "Budget", rarity: "Common", description: "Blue scratch knife design.", inStock: 1, imageUrl: getProductImage("Blue Scratch") },
  { id: generateId("Red Scratch"), name: "Red Scratch", price: 17, category: "Budget", rarity: "Common", description: "Red scratch knife design.", inStock: 1, imageUrl: getProductImage("Red Scratch") },
  { id: generateId("Green Fire"), name: "Green Fire", price: 17, category: "Budget", rarity: "Uncommon", description: "Green fire effect knife.", inStock: 1, imageUrl: getProductImage("Green Fire") },
  { id: generateId("Green Marble"), name: "Green Marble", price: 17, category: "Budget", rarity: "Common", description: "Elegant green marble knife.", inStock: 1, imageUrl: getProductImage("Green Marble") },
  { id: generateId("Cane Knife"), name: "Cane Knife", price: 17, category: "Budget", rarity: "Common", description: "Candy cane styled knife.", inStock: 1, imageUrl: getProductImage("Cane Knife") },
  { id: generateId("Vampire"), name: "Vampire", price: 17, category: "Budget", rarity: "Uncommon", description: "Dark vampire knife.", inStock: 1, imageUrl: getProductImage("Vampire") },
  { id: generateId("Elite"), name: "Elite", price: 17, category: "Budget", rarity: "Common", description: "Classic elite knife.", inStock: 1, imageUrl: getProductImage("Elite") },
  { id: generateId("Cavern Knife"), name: "Cavern Knife", price: 17, category: "Budget", rarity: "Uncommon", description: "Dark cavern knife.", inStock: 1, imageUrl: getProductImage("Cavern Knife") },
  { id: generateId("TNL"), name: "TNL", price: 17, category: "Budget", rarity: "Common", description: "TNL special knife.", inStock: 1, imageUrl: getProductImage("TNL") },
  { id: generateId("Patrick"), name: "Patrick", price: 17, category: "Budget", rarity: "Common", description: "Patrick themed knife.", inStock: 1, imageUrl: getProductImage("Patrick") },
  { id: generateId("Elf Knife"), name: "Elf Knife", price: 17, category: "Budget", rarity: "Common", description: "Festive elf knife.", inStock: 1, imageUrl: getProductImage("Elf Knife") },
  { id: generateId("Ornament Knife"), name: "Ornament Knife", price: 17, category: "Budget", rarity: "Common", description: "Christmas ornament knife.", inStock: 1, imageUrl: getProductImage("Ornament Knife") },
  { id: generateId("2015"), name: "2015", price: 17, category: "Budget", rarity: "Rare", description: "Classic 2015 knife.", inStock: 1, imageUrl: getProductImage("2015") },
  { id: generateId("Snowflake"), name: "Snowflake", price: 17, category: "Budget", rarity: "Common", description: "Icy snowflake knife.", inStock: 1, imageUrl: getProductImage("Snowflake") },
  { id: generateId("Infected"), name: "Infected", price: 17, category: "Budget", rarity: "Uncommon", description: "Infected green knife.", inStock: 1, imageUrl: getProductImage("Infected") },
  { id: generateId("Web"), name: "Web", price: 17, category: "Budget", rarity: "Common", description: "Spider web knife.", inStock: 1, imageUrl: getProductImage("Web") },
  { id: generateId("Santa's Magic"), name: "Santa's Magic", price: 17, category: "Budget", rarity: "Uncommon", description: "Magical Santa knife.", inStock: 1, imageUrl: getProductImage("Santa's Magic") },
  { id: generateId("Santa's Spirit"), name: "Santa's Spirit", price: 17, category: "Budget", rarity: "Uncommon", description: "Spirit of Santa knife.", inStock: 1, imageUrl: null },
  { id: generateId("Ripper Knife"), name: "Ripper Knife", price: 17, category: "Budget", rarity: "Common", description: "Sharp ripper knife.", inStock: 1, imageUrl: getProductImage("Ripper Knife") },
  { id: generateId("Tree Knife"), name: "Tree Knife", price: 17, category: "Budget", rarity: "Common", description: "Nature tree knife.", inStock: 1, imageUrl: getProductImage("Tree Knife") },
  { id: generateId("Santa Knife"), name: "Santa Knife", price: 17, category: "Budget", rarity: "Common", description: "Jolly Santa knife.", inStock: 1, imageUrl: getProductImage("Santa Knife") },
  { id: generateId("Goo"), name: "Goo", price: 17, category: "Budget", rarity: "Uncommon", description: "Slimy goo knife.", inStock: 1, imageUrl: getProductImage("Goo") },
  { id: generateId("Eyeball"), name: "Eyeball", price: 17, category: "Budget", rarity: "Uncommon", description: "Spooky eyeball knife.", inStock: 1, imageUrl: getProductImage("Eyeball") },
  { id: generateId("Cane Gun"), name: "Cane Gun", price: 17, category: "Budget", rarity: "Common", description: "Candy cane gun.", inStock: 1, imageUrl: getProductImage("Cane Gun") },

  { id: generateId("Shadow"), name: "Shadow", price: 26, category: "Standard", rarity: "Rare", description: "Dark shadow-themed knife with ethereal effects.", inStock: 1, imageUrl: getProductImage("Shadow") },
  { id: generateId("Phoenix"), name: "Phoenix", price: 26, category: "Standard", rarity: "Legendary", description: "Fiery phoenix knife rises from ashes.", inStock: 1, imageUrl: getProductImage("Phoenix") },
  { id: generateId("Nobledragon"), name: "Nobledragon", price: 26, category: "Standard", rarity: "Legendary", description: "Majestic noble dragon pet.", inStock: 1, imageUrl: getProductImage("Nobledragon") },
  { id: generateId("Overseer Eye"), name: "Overseer Eye", price: 26, category: "Standard", rarity: "Rare", description: "All-seeing overseer eye.", inStock: 1, imageUrl: getProductImage("Overseer Eye") },
  { id: generateId("Jetstream"), name: "Jetstream", price: 26, category: "Standard", rarity: "Rare", description: "Fast jetstream knife.", inStock: 1, imageUrl: getProductImage("Jetstream") },
  { id: generateId("Icey"), name: "Icey", price: 26, category: "Standard", rarity: "Rare", description: "Frozen icy knife.", inStock: 1, imageUrl: getProductImage("Icey") },
  { id: generateId("Steambird"), name: "Steambird", price: 26, category: "Standard", rarity: "Rare", description: "Steampunk bird pet.", inStock: 1, imageUrl: getProductImage("Steambird") },
  { id: generateId("Red Seer"), name: "Red Seer", price: 26, category: "Standard", rarity: "Rare", description: "Crimson red seer knife.", inStock: 1, imageUrl: getProductImage("Red Seer") },
  { id: generateId("Blue Seer"), name: "Blue Seer", price: 26, category: "Standard", rarity: "Rare", description: "Azure blue seer knife.", inStock: 1, imageUrl: getProductImage("Blue Seer") },
  { id: generateId("Ornament2 Set"), name: "Ornament2 Set", price: 26, category: "Standard", rarity: "Rare", description: "Complete ornament set.", inStock: 1, imageUrl: getProductImage("Ornament2 Set") },
  { id: generateId("Toxic Set"), name: "Toxic Set", price: 26, category: "Standard", rarity: "Rare", description: "Poisonous toxic set.", inStock: 1, imageUrl: getProductImage("Toxic Set") },
  { id: generateId("Aurora Set"), name: "Aurora Set", price: 26, category: "Standard", rarity: "Legendary", description: "Beautiful aurora set.", inStock: 1, imageUrl: getProductImage("Aurora Set") },
  { id: generateId("Frostbird"), name: "Frostbird", price: 26, category: "Standard", rarity: "Rare", description: "Frozen frost bird pet.", inStock: 1, imageUrl: getProductImage("Frostbird") },
  { id: generateId("Seer"), name: "Seer", price: 26, category: "Standard", rarity: "Rare", description: "Classic seer knife.", inStock: 1, imageUrl: getProductImage("Seer") },
  { id: generateId("Gemstone"), name: "Gemstone", price: 23, category: "Standard", rarity: "Rare", description: "Precious gemstone knife.", inStock: 1, imageUrl: getProductImage("Gemstone") },
  { id: generateId("Xmas"), name: "Xmas", price: 23, category: "Standard", rarity: "Rare", description: "Festive Christmas knife.", inStock: 1, imageUrl: getProductImage("Xmas") },
  { id: generateId("Virtual"), name: "Virtual", price: 23, category: "Standard", rarity: "Legendary", description: "Digital virtual knife.", inStock: 1, imageUrl: getProductImage("Virtual") },
  { id: generateId("Gingerblade"), name: "Gingerblade", price: 19, category: "Standard", rarity: "Rare", description: "Sweet gingerbread blade.", inStock: 1, imageUrl: getProductImage("Gingerblade") },
  { id: generateId("Ice Flake"), name: "Ice Flake", price: 25, category: "Standard", rarity: "Rare", description: "Frozen ice flake knife.", inStock: 1, imageUrl: getProductImage("Ice Flake") },

  { id: generateId("Icewing"), name: "Icewing", price: 18, category: "Godly", rarity: "Godly", description: "Legendary Icewing with frozen aura.", inStock: 1, imageUrl: getProductImage("Icewing") },
  { id: generateId("Fang"), name: "Fang", price: 18, category: "Godly", rarity: "Godly", description: "Deadly Fang knife with sharp edges.", inStock: 1, imageUrl: getProductImage("Fang") },
  { id: generateId("Heat"), name: "Heat", price: 18, category: "Godly", rarity: "Godly", description: "Blazing Heat knife burns bright.", inStock: 1, imageUrl: getProductImage("Heat") },
  { id: generateId("Tides"), name: "Tides", price: 18, category: "Godly", rarity: "Godly", description: "Ocean Tides knife flows eternally.", inStock: 1, imageUrl: getProductImage("Tides") },
  { id: generateId("Spider"), name: "Spider", price: 18, category: "Godly", rarity: "Godly", description: "Venomous Spider knife design.", inStock: 1, imageUrl: getProductImage("Spider") },
  { id: generateId("Eternal"), name: "Eternal", price: 18, category: "Godly", rarity: "Godly", description: "Timeless Eternal knife.", inStock: 1, imageUrl: getProductImage("Eternal") },
  { id: generateId("Eternal II"), name: "Eternal II", price: 18, category: "Godly", rarity: "Godly", description: "Enhanced Eternal II knife.", inStock: 1, imageUrl: getProductImage("Eternal II") },
  { id: generateId("Eternal III"), name: "Eternal III", price: 18, category: "Godly", rarity: "Godly", description: "Superior Eternal III knife.", inStock: 1, imageUrl: getProductImage("Eternal III") },
  { id: generateId("Eternal IV"), name: "Eternal IV", price: 18, category: "Godly", rarity: "Godly", description: "Ultimate Eternal IV knife.", inStock: 1, imageUrl: getProductImage("Eternal IV") },
  { id: generateId("Eternalcane"), name: "Eternalcane", price: 18, category: "Godly", rarity: "Godly", description: "Festive Eternalcane knife.", inStock: 1, imageUrl: getProductImage("Eternalcane") },
  { id: generateId("Hallow's Edge"), name: "Hallow's Edge", price: 18, category: "Godly", rarity: "Godly", description: "Spooky Hallow's Edge knife.", inStock: 1, imageUrl: getProductImage("Hallow's Edge") },
  { id: generateId("Frostbite"), name: "Frostbite", price: 15, category: "Godly", rarity: "Godly", description: "Chilling Frostbite knife.", inStock: 1, imageUrl: getProductImage("Frostbite") },
  { id: generateId("Frostsaber"), name: "Frostsaber", price: 15, category: "Godly", rarity: "Godly", description: "Frozen Frostsaber weapon.", inStock: 1, imageUrl: getProductImage("Frostsaber") },
  { id: generateId("Flames"), name: "Flames", price: 14, category: "Godly", rarity: "Godly", description: "Burning Flames knife.", inStock: 1, imageUrl: getProductImage("Flames") },
  { id: generateId("Boneblade"), name: "Boneblade", price: 14, category: "Godly", rarity: "Godly", description: "Skeletal Boneblade knife.", inStock: 1, imageUrl: getProductImage("Boneblade") },
  { id: generateId("Chill"), name: "Chill", price: 14, category: "Godly", rarity: "Godly", description: "Cool Chill knife.", inStock: 1, imageUrl: getProductImage("Chill") },
  { id: generateId("Handsaw"), name: "Handsaw", price: 14, category: "Godly", rarity: "Godly", description: "Sharp Handsaw knife.", inStock: 1, imageUrl: getProductImage("Handsaw") },
  { id: generateId("Chroma Fire Bat"), name: "Chroma Fire Bat", price: 14, category: "Godly", rarity: "Chroma", description: "Chromatic fire bat pet.", inStock: 1, imageUrl: getProductImage("Chroma Fire Bat") },
  { id: generateId("Chroma Fire Dog"), name: "Chroma Fire Dog", price: 14, category: "Godly", rarity: "Chroma", description: "Chromatic fire dog pet.", inStock: 1, imageUrl: getProductImage("Chroma Fire Dog") },
  { id: generateId("Chroma Fire Cat"), name: "Chroma Fire Cat", price: 14, category: "Godly", rarity: "Chroma", description: "Chromatic fire cat pet.", inStock: 1, imageUrl: getProductImage("Chroma Fire Cat") },
  { id: generateId("Chroma Fire Pig"), name: "Chroma Fire Pig", price: 14, category: "Godly", rarity: "Chroma", description: "Chromatic fire pig pet.", inStock: 1, imageUrl: getProductImage("Chroma Fire Pig") },
  { id: generateId("Chroma Fire Fox"), name: "Chroma Fire Fox", price: 14, category: "Godly", rarity: "Chroma", description: "Chromatic fire fox pet.", inStock: 1, imageUrl: getProductImage("Chroma Fire Fox") },
  { id: generateId("Chroma Fire Bear"), name: "Chroma Fire Bear", price: 14, category: "Godly", rarity: "Chroma", description: "Chromatic fire bear pet.", inStock: 1, imageUrl: getProductImage("Chroma Fire Bear") },
  { id: generateId("Chroma Fire Bunny"), name: "Chroma Fire Bunny", price: 14, category: "Godly", rarity: "Chroma", description: "Chromatic fire bunny pet.", inStock: 1, imageUrl: getProductImage("Chroma Fire Bunny") },
  { id: generateId("Ice Shard"), name: "Ice Shard", price: 13, category: "Godly", rarity: "Godly", description: "Frozen Ice Shard knife.", inStock: 1, imageUrl: getProductImage("Ice Shard") },
  { id: generateId("Winters Edge"), name: "Winters Edge", price: 12, category: "Godly", rarity: "Godly", description: "Cold Winter's Edge knife.", inStock: 1, imageUrl: getProductImage("Winters Edge") },

  { id: generateId("Vampire's Edge"), name: "Vampire's Edge", price: 44, category: "Ancient", rarity: "Ancient", description: "Ancient vampire-themed edge blade.", inStock: 1, imageUrl: getProductImage("Vampire's Edge") },
  { id: generateId("Green Luger"), name: "Green Luger", price: 44, category: "Ancient", rarity: "Ancient", description: "Classic green Luger gun.", inStock: 1, imageUrl: getProductImage("Green Luger") },
  { id: generateId("Battleaxe"), name: "Battleaxe", price: 44, category: "Ancient", rarity: "Ancient", description: "Mighty battleaxe weapon.", inStock: 1, imageUrl: getProductImage("Battleaxe") },
  { id: generateId("Nightblade"), name: "Nightblade", price: 44, category: "Ancient", rarity: "Ancient", description: "Dark nightblade knife.", inStock: 1, imageUrl: getProductImage("Nightblade") },
  { id: generateId("Bioblade"), name: "Bioblade", price: 44, category: "Ancient", rarity: "Ancient", description: "Biological bioblade weapon.", inStock: 1, imageUrl: getProductImage("Bioblade") },
  { id: generateId("Saw"), name: "Saw", price: 44, category: "Ancient", rarity: "Ancient", description: "Sharp saw blade.", inStock: 1, imageUrl: getProductImage("Saw") },
  { id: generateId("Pumpking"), name: "Pumpking", price: 44, category: "Ancient", rarity: "Ancient", description: "Spooky pumpkin king.", inStock: 1, imageUrl: getProductImage("Pumpking") },
  { id: generateId("Blood"), name: "Blood", price: 44, category: "Ancient", rarity: "Ancient", description: "Crimson blood knife.", inStock: 1, imageUrl: getProductImage("Blood") },
  { id: generateId("Heart Pet"), name: "Heart Pet", price: 44, category: "Ancient", rarity: "Ancient", description: "Loving heart pet.", inStock: 1, imageUrl: getProductImage("Heart Pet") },
  { id: generateId("Cookiecane"), name: "Cookiecane", price: 44, category: "Ancient", rarity: "Ancient", description: "Sweet cookie cane.", inStock: 1, imageUrl: getProductImage("Cookiecane") },
  { id: generateId("Pixel"), name: "Pixel", price: 36, category: "Ancient", rarity: "Ancient", description: "Retro pixel knife.", inStock: 1, imageUrl: getProductImage("Pixel") },
  { id: generateId("Ginger Luger"), name: "Ginger Luger", price: 36, category: "Ancient", rarity: "Ancient", description: "Gingerbread Luger gun.", inStock: 1, imageUrl: getProductImage("Ginger Luger") },
  { id: generateId("Hallowgun"), name: "Hallowgun", price: 36, category: "Ancient", rarity: "Ancient", description: "Spooky Halloween gun.", inStock: 1, imageUrl: getProductImage("Hallowgun") },
  { id: generateId("Ghost"), name: "Ghost", price: 35, category: "Ancient", rarity: "Ancient", description: "Ethereal ghost knife.", inStock: 1, imageUrl: getProductImage("Ghost") },
  { id: generateId("Deathspeaker"), name: "Deathspeaker", price: 35, category: "Ancient", rarity: "Ancient", description: "Deadly deathspeaker weapon.", inStock: 1, imageUrl: getProductImage("Deathspeaker") },
  { id: generateId("Electro"), name: "Electro", price: 35, category: "Ancient", rarity: "Ancient", description: "Electric electro knife.", inStock: 1, imageUrl: getProductImage("Electro") },
  { id: generateId("Sammy"), name: "Sammy", price: 35, category: "Ancient", rarity: "Ancient", description: "Classic Sammy pet.", inStock: 1, imageUrl: getProductImage("Sammy") },
  { id: generateId("Prismatic"), name: "Prismatic", price: 35, category: "Ancient", rarity: "Ancient", description: "Rainbow prismatic knife.", inStock: 1, imageUrl: getProductImage("Prismatic") },
  { id: generateId("Prince"), name: "Prince", price: 35, category: "Ancient", rarity: "Ancient", description: "Royal prince knife.", inStock: 1, imageUrl: getProductImage("Prince") },
  { id: generateId("Peppermint"), name: "Peppermint", price: 35, category: "Ancient", rarity: "Ancient", description: "Sweet peppermint knife.", inStock: 1, imageUrl: getProductImage("Peppermint") },
  { id: generateId("Wrapping Paper Bundle"), name: "Wrapping Paper Bundle", price: 35, category: "Ancient", rarity: "Ancient", description: "Festive wrapping paper set.", inStock: 1, imageUrl: getProductImage("Wrapping Paper Bundle") },
  { id: generateId("Logchopper"), name: "Logchopper", price: 32, category: "Ancient", rarity: "Ancient", description: "Powerful log chopper axe.", inStock: 1, imageUrl: getProductImage("Logchopper") },
  { id: generateId("Lugercane"), name: "Lugercane", price: 32, category: "Ancient", rarity: "Ancient", description: "Candy cane Luger gun.", inStock: 1, imageUrl: getProductImage("Lugercane") },
  { id: generateId("Old Glory"), name: "Old Glory", price: 32, category: "Ancient", rarity: "Ancient", description: "Patriotic old glory knife.", inStock: 1, imageUrl: getProductImage("Old Glory") },
  { id: generateId("BattleAxe II"), name: "BattleAxe II", price: 32, category: "Ancient", rarity: "Ancient", description: "Enhanced battleaxe II.", inStock: 1, imageUrl: getProductImage("BattleAxe II") },
  { id: generateId("Nebula"), name: "Nebula", price: 27, category: "Ancient", rarity: "Ancient", description: "Cosmic nebula knife.", inStock: 1, imageUrl: getProductImage("Nebula") },
  { id: generateId("Slasher"), name: "Slasher", price: 27, category: "Ancient", rarity: "Ancient", description: "Sharp slasher knife.", inStock: 1, imageUrl: getProductImage("Slasher") },
  { id: generateId("Minty"), name: "Minty", price: 27, category: "Ancient", rarity: "Ancient", description: "Fresh minty knife.", inStock: 1, imageUrl: getProductImage("Minty") },
  { id: generateId("JingleGun"), name: "JingleGun", price: 27, category: "Ancient", rarity: "Ancient", description: "Festive jingle gun.", inStock: 1, imageUrl: getProductImage("JingleGun") },
  { id: generateId("Clockwork"), name: "Clockwork", price: 27, category: "Ancient", rarity: "Ancient", description: "Mechanical clockwork knife.", inStock: 1, imageUrl: getProductImage("Clockwork") },

  { id: generateId("Chroma Knife Set"), name: "Chroma Knife Set", price: 269, category: "Bundles", rarity: "Chroma", description: "Complete set of chromatic knives with rainbow effects.", inStock: 1, imageUrl: getProductImage("Chroma Knife Set") },
  { id: generateId("Bat Bundle"), name: "Bat", price: 269, category: "Bundles", rarity: "Legendary", description: "Exclusive bat-themed bundle.", inStock: 1, imageUrl: getProductImage("Bat Bundle") },
  { id: generateId("Sparkle Set"), name: "Sparkle Set", price: 269, category: "Bundles", rarity: "Legendary", description: "Sparkling set of items.", inStock: 1, imageUrl: getProductImage("Sparkle Set") },
  { id: generateId("Brontosaurus"), name: "Brontosaurus", price: 269, category: "Bundles", rarity: "Legendary", description: "Prehistoric brontosaurus bundle.", inStock: 1, imageUrl: getProductImage("Brontosaurus") },
  { id: generateId("Borealis"), name: "Borealis", price: 311, category: "Bundles", rarity: "Legendary", description: "Northern lights borealis set.", inStock: 1, imageUrl: getProductImage("Borealis") },
  { id: generateId("Mega Chroma Knives Bundle"), name: "Mega Chroma Knives Bundle", price: 359, category: "Bundles", rarity: "Chroma", description: "Ultimate mega chroma knife collection.", inStock: 1, imageUrl: getProductImage("Mega Chroma Knives Bundle") },
  { id: generateId("Chroma Bringer Set"), name: "Chroma Bringer Set", price: 359, category: "Bundles", rarity: "Chroma", description: "Chromatic bringer weapon set.", inStock: 1, imageUrl: getProductImage("Chroma Bringer Set") },
  { id: generateId("Ice Bundle"), name: "Ice Bundle", price: 378, category: "Bundles", rarity: "Legendary", description: "Frozen ice themed bundle.", inStock: 1, imageUrl: getProductImage("Ice Bundle") },
  { id: generateId("Icepiercer"), name: "Icepiercer", price: 383, category: "Bundles", rarity: "Legendary", description: "Sharp icepiercer weapon bundle.", inStock: 1, imageUrl: getProductImage("Icepiercer") },
  { id: generateId("Scythe Set"), name: "Scythe Set", price: 449, category: "Bundles", rarity: "Ancient", description: "Deadly scythe weapon set.", inStock: 1, imageUrl: getProductImage("Scythe Set") },
  { id: generateId("Full Swirly Bundle"), name: "Full Swirly Bundle", price: 449, category: "Bundles", rarity: "Legendary", description: "Complete swirly pattern bundle.", inStock: 1, imageUrl: getProductImage("Full Swirly Bundle") },
  { id: generateId("Halloween Bundle"), name: "Halloween Bundle", price: 449, category: "Bundles", rarity: "Legendary", description: "Spooky Halloween collection.", inStock: 1, imageUrl: getProductImage("Halloween Bundle") },
  { id: generateId("Candy Set"), name: "Candy Set", price: 449, category: "Bundles", rarity: "Legendary", description: "Sweet candy themed set.", inStock: 1, imageUrl: getProductImage("Candy Set") },
  { id: generateId("Ancient Mega Bundle"), name: "Ancient Mega Bundle", price: 494, category: "Bundles", rarity: "Ancient", description: "Massive ancient item collection.", inStock: 1, imageUrl: getProductImage("Ancient Mega Bundle") },
  { id: generateId("Harvester"), name: "Harvester", price: 495, category: "Bundles", rarity: "Ancient", description: "Powerful harvester weapon.", inStock: 1, imageUrl: getProductImage("Harvester") },
  { id: generateId("Full Elderwood Bundle"), name: "Full Elderwood Bundle", price: 503, category: "Bundles", rarity: "Ancient", description: "Complete elderwood collection.", inStock: 1, imageUrl: getProductImage("Full Elderwood Bundle") },
  { id: generateId("Borealis Set"), name: "Borealis Set", price: 626, category: "Bundles", rarity: "Legendary", description: "Complete borealis themed set.", inStock: 1, imageUrl: getProductImage("Borealis Set") },
  { id: generateId("Super Luger Bundle"), name: "Super Luger Bundle", price: 629, category: "Bundles", rarity: "Ancient", description: "Ultimate Luger gun collection.", inStock: 1, imageUrl: getProductImage("Super Luger Bundle") },
  { id: generateId("Chroma Gun Set"), name: "Chroma Gun Set", price: 675, category: "Bundles", rarity: "Chroma", description: "Complete chromatic gun collection.", inStock: 1, imageUrl: getProductImage("Chroma Gun Set") },
  { id: generateId("Full Ice Bundle"), name: "Full Ice Bundle", price: 675, category: "Bundles", rarity: "Legendary", description: "Ultimate frozen ice bundle.", inStock: 1, imageUrl: getProductImage("Full Ice Bundle") },

  { id: generateId("Bat Bundle Royal"), name: "Bat Bundle", price: 755, category: "Royal", rarity: "Ancient", description: "Premium bat themed bundle.", inStock: 1, imageUrl: getProductImage("Bat Bundle") },
  { id: generateId("Corrupt"), name: "Corrupt", price: 1031, category: "Royal", rarity: "Ancient", description: "Corrupted dark weapon set.", inStock: 1, imageUrl: getProductImage("Corrupt") },
  { id: generateId("Christmas Collection"), name: "Christmas Collection", price: 1169, category: "Royal", rarity: "Legendary", description: "Complete Christmas themed collection.", inStock: 1, imageUrl: getProductImage("Christmas Collection") },
  { id: generateId("Mega Chroma Bundle"), name: "Mega Chroma Bundle", price: 1259, category: "Royal", rarity: "Chroma", description: "Ultimate mega chroma collection.", inStock: 1, imageUrl: getProductImage("Mega Chroma Bundle") },
  { id: generateId("Harvester Bundle"), name: "Harvester Bundle", price: 1373, category: "Royal", rarity: "Ancient", description: "Complete harvester bundle.", inStock: 1, imageUrl: getProductImage("Harvester Bundle") },
  { id: generateId("Golden Bundle"), name: "Golden Bundle", price: 1709, category: "Royal", rarity: "Legendary", description: "Prestigious golden item bundle.", inStock: 1, imageUrl: getProductImage("Golden Bundle") },
  { id: generateId("Best Bundle"), name: "Best Bundle", price: 2699, category: "Royal", rarity: "Ancient", description: "The best value bundle available.", inStock: 1, imageUrl: getProductImage("Best Bundle") },
  { id: generateId("Small Set"), name: "Small Set", price: 5129, category: "Royal", rarity: "Chroma", description: "Exclusive small but premium set.", inStock: 1, imageUrl: getProductImage("Small Set") },
];

export function getProductById(id: string): Product | undefined {
  return allProducts.find(p => p.id === id);
}

export function getProductsByCategory(category: Category): Product[] {
  return allProducts.filter(p => p.category === category);
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase();
  return allProducts.filter(
    p => p.name.toLowerCase().includes(lowerQuery) || 
         p.description?.toLowerCase().includes(lowerQuery) ||
         p.category.toLowerCase().includes(lowerQuery) ||
         p.rarity.toLowerCase().includes(lowerQuery)
  );
}

export function getTopSellingProducts(): Product[] {
  return allProducts.filter(p => p.rarity === "Godly" || p.rarity === "Ancient").slice(0, 8);
}

export function getFeaturedProducts(): Product[] {
  return allProducts.filter(p => p.category === "Bundles" || p.category === "Royal").slice(0, 4);
}

Object.keys(categoryInfo).forEach(cat => {
  categoryInfo[cat].itemCount = allProducts.filter(p => p.category === cat).length;
});
