import type { Product } from "./schema";

function generateId(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-');
}

const productImages: Record<string, string> = {
  "2015": "/products/2015-commons-899_500x500.webp.png",
  "8-bit-bundle": "/products/8-bit-bundle-godlies-441_500x500.webp.png",
  "america-bundle": "/products/america-bundle-godlies-449_500x500.webp.png",
  "amerilaser": "/products/amerilaser-godlies-318_500x500.webp.png",
  "ancient-mega-bundle": "/products/ancient-mega-bundle-ancients-526_500x500.webp.png",
  "aurora-set": "/products/aurora-set-commons-882_500x500.webp.png",
  "badger": "/products/badger-commons-226_500x500.webp.png",
  "bat-bundle": "/products/bat-bundle-legendaries-643_500x500.webp.png",
  "bat": "/products/bat-godlies-929_500x500.webp.png",
  "battleaxe-ii": "/products/battleaxe-ii-godlies-917_500x500.webp.png",
  "battleaxe-set": "/products/battleaxe-set-ancients-115_500x500.webp.png",
  "battleaxe": "/products/battleaxe-ii-godlies-917_500x500.webp.png",
  "batwing": "/products/batwing-ancients-111_500x500.webp.png",
  "bauble": "/products/bauble-godlies-220_500x500.webp.png",
  "bioblade": "/products/bioblade-godlies-705_500x500.webp.png",
  "blood": "/products/blood-vintages-231_500x500.webp.png",
  "bloom-set": "/products/bloom-set-godlies-175_500x500.webp.png",
  "blossom": "/products/blossom-commons-100_500x500.webp.png",
  "blue-elite": "/products/blue-elite-legendaries-299_500x500.webp.png",
  "blue-scratch": "/products/blue-scratch-legendaries-541_500x500.webp.png",
  "blue-seer": "/products/blue-seer-godlies-852_500x500.webp.png",
  "boneblade": "/products/boneblade-godlies-838_500x500.webp.png",
  "borealis": "/products/borealis-godlies-277_500x500.webp.png",
  "borealis-set": "/products/borealis-set-godlies-222_500x500.webp.png",
  "candleflame": "/products/candleflame-godlies-541_500x500.webp.png",
  "candy": "/products/candy-godlies-518_500x500.webp.png",
  "candy-set": "/products/candy-set-godlies-947_500x500.webp.png",
  "celestial": "/products/celestial-ancients-913_500x500.webp.png",
  "chill": "/products/chill-godlies-937_500x500.webp.png",
  "chroma-bringer-set": "/products/chroma-bringer-set-chromas-488_500x500.webp.png",
  "chroma-candleflame": "/products/chroma-candleflame-chromas-171_500x500.webp.png",
  "chroma-darkbringer": "/products/chroma-darkbringer-chromas-362_500x500.webp.png",
  "chroma-deathshard": "/products/chroma-deathshard-chromas-199_500x500.webp.png",
  "chroma-elderwood-blade": "/products/chroma-elderwood-blade-chromas-552_500x500.webp.png",
  "chroma-fire-pets-set": "/products/chroma-fire-pets-set-chromas-679_500x500.webp.png",
  "chroma-gemstone": "/products/chroma-gemstone-chromas-567_500x500.webp.png",
  "chroma-gingerblade": "/products/chroma-gingerblade-chromas-728_500x500.webp.png",
  "chroma-heat": "/products/chroma-heat-chromas-906_500x500.webp.png",
  "chroma-laser": "/products/chroma-laser-chromas-365_500x500.webp.png",
  "chroma-lightbringer": "/products/chroma-lightbringer-chromas-827_500x500.webp.png",
  "chroma-luger": "/products/chroma-luger-chromas-194_500x500.webp.png",
  "chroma-saw": "/products/chroma-saw-chromas-425_500x500.webp.png",
  "chroma-seer": "/products/chroma-seer-chromas-832_500x500.webp.png",
  "chroma-shark": "/products/chroma-shark-chromas-323_500x500.webp.png",
  "clockwork": "/products/clockwork-godlies-668_500x500.webp.png",
  "corrupt": "/products/corrupt-uniques-124_500x500.webp.png",
  "darkbringer": "/products/darkbringer-godlies-178_500x500.webp.png",
  "deathshard": "/products/deathshard-godlies-931_500x500.webp.png",
  "elderwood-blade": "/products/elderwood-blade-godlies-898_500x500.webp.png",
  "elderwood-revolver": "/products/elderwood-revolver-godlies-184_500x500.webp.png",
  "elderwood-scythe": "/products/elderwood-scythe-godlies-250_500x500.webp.png",
  "elderwood-set": "/products/elderwood-set-ancients-627_500x500.webp.png",
  "eternal": "/products/eternal-godlies-902_500x500.webp.png",
  "eternal-ii": "/products/eternal-ii-godlies-534_500x500.webp.png",
  "eternal-iii": "/products/eternal-iii-godlies-908_500x500.webp.png",
  "eternal-iv": "/products/eternal-iv-godlies-669_500x500.webp.png",
  "eternal-set": "/products/eternal-set-godlies-719_500x500.webp.png",
  "fang": "/products/fang-godlies-268_500x500.webp.png",
  "flames": "/products/flames-godlies-691_500x500.webp.png",
  "frostbite": "/products/frostbite-godlies-356_500x500.webp.png",
  "frostsaber": "/products/frostsaber-godlies-484_500x500.webp.png",
  "gemstone": "/products/gemstone-godlies-960_500x500.webp.png",
  "ghost": "/products/ghost-vintages-587_500x500.webp.png",
  "gingerblade": "/products/gingerblade-godlies-849_500x500.webp.png",
  "ginger-luger": "/products/ginger-luger-godlies-998_500x500.webp.png",
  "gingerscope": "/products/gingerscope-ancients-670_500x500.webp.png",
  "green-luger": "/products/green-luger-godlies-224_500x500.webp.png",
  "hallowgun": "/products/hallowgun-godlies-770_500x500.webp.png",
  "hallows-blade": "/products/hallows-blade-godlies-348_500x500.webp.png",
  "hallowscythe": "/products/hallowscythe-ancients-977_500x500.webp.png",
  "hallows-edge": "/products/hallows-edge-godlies-686_500x500.webp.png",
  "hallow-set": "/products/hallow-set-ancients-152_500x500.webp.png",
  "handsaw": "/products/handsaw-godlies-290_500x500.webp.png",
  "harvester": "/products/harvester-ancients-884_500x500.webp.png",
  "heartblade": "/products/heartblade-godlies-347_500x500.webp.png",
  "heat": "/products/heat-godlies-740_500x500.webp.png",
  "icebeam": "/products/icebeam-godlies-477_500x500.webp.png",
  "iceblaster": "/products/iceblaster-godlies-396_500x500.webp.png",
  "icebreaker": "/products/icebreaker-godlies-280_500x500.webp.png",
  "icepiercer": "/products/icepiercer-ancients-671_500x500.webp.png",
  "icewing": "/products/icewing-ancients-871_500x500.webp.png",
  "laser": "/products/laser-godlies-694_500x500.webp.png",
  "lightbringer": "/products/lightbringer-godlies-558_500x500.webp.png",
  "logchopper": "/products/logchopper-ancients-765_500x500.webp.png",
  "luger": "/products/luger-godlies-872_500x500.webp.png",
  "lugercane": "/products/lugercane-godlies-578_500x500.webp.png",
  "minty": "/products/minty-godlies-358_500x500.webp.png",
  "nebula": "/products/nebula-godlies-938_500x500.webp.png",
  "nightblade": "/products/nightblade-godlies-828_500x500.webp.png",
  "old-glory": "/products/old-glory-godlies-673_500x500.webp.png",
  "peppermint": "/products/peppermint-godlies-111_500x500.webp.png",
  "phoenix": "/products/phoenix-godlies-868_500x500.webp.png",
  "pixel": "/products/pixel-godlies-637_500x500.webp.png",
  "prince": "/products/prince-vintages-220_500x500.webp.png",
  "prismatic": "/products/prismatic-godlies-618_500x500.webp.png",
  "pumpking": "/products/pumpking-godlies-606_500x500.webp.png",
  "red-seer": "/products/red-seer-godlies-733_500x500.webp.png",
  "sammy": "/products/sammy-godlies-556_500x500.webp.png",
  "saw": "/products/saw-godlies-561_500x500.webp.png",
  "seer": "/products/seer-godlies-457_500x500.webp.png",
  "shadow": "/products/shadow-vintages-821_500x500.webp.png",
  "shark": "/products/shark-godlies-878_500x500.webp.png",
  "slasher": "/products/slasher-godlies-511_500x500.webp.png",
  "snowflake": "/products/snowflake-godlies-816_500x500.webp.png",
  "spider": "/products/spider-godlies-398_500x500.webp.png",
  "sugar": "/products/sugar-godlies-190_500x500.webp.png",
  "tides": "/products/tides-godlies-963_500x500.webp.png",
  "vampires-edge": "/products/vampires-edge-godlies-398_500x500.webp.png",
  "vampires-axe": "/products/vampires-axe-ancients-308_500x500.webp.png",
  "virtual": "/products/virtual-godlies-577_500x500.webp.png",
  "winters-edge": "/products/winters-edge-godlies-255_500x500.webp.png",
  "xmas": "/products/xmas-godlies-125_500x500.webp.png",
};

function getProductImage(name: string): string | null {
  const key = name.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  return productImages[key] || null;
}

export const seedProducts: Product[] = [
  { id: generateId("Blue Elite"), name: "Blue Elite", price: 17, category: "Budget", rarity: "Common", description: "A sleek blue elite knife with sharp edges.", inStock: 100, imageUrl: getProductImage("Blue Elite") },
  { id: generateId("Green Elite"), name: "Green Elite", price: 17, category: "Budget", rarity: "Common", description: "A vibrant green elite knife.", inStock: 100, imageUrl: getProductImage("Green Elite") },
  { id: generateId("Blossom"), name: "Blossom", price: 17, category: "Budget", rarity: "Common", description: "Beautiful floral blossom knife.", inStock: 100, imageUrl: getProductImage("Blossom") },
  { id: generateId("Hallows Blade"), name: "Hallows Blade", price: 17, category: "Budget", rarity: "Uncommon", description: "Spooky Halloween-themed blade.", inStock: 100, imageUrl: getProductImage("Hallows Blade") },
  { id: generateId("Badger"), name: "Badger", price: 17, category: "Budget", rarity: "Common", description: "Cute badger pet.", inStock: 100, imageUrl: getProductImage("Badger") },
  
  { id: generateId("Seer"), name: "Seer", price: 35, category: "Standard", rarity: "Godly", description: "The classic godly knife that started it all.", inStock: 100, imageUrl: getProductImage("Seer") },
  { id: generateId("Fang"), name: "Fang", price: 40, category: "Standard", rarity: "Godly", description: "Sharp fang-shaped godly knife.", inStock: 100, imageUrl: getProductImage("Fang") },
  { id: generateId("Saw"), name: "Saw", price: 45, category: "Standard", rarity: "Godly", description: "Industrial saw-blade godly knife.", inStock: 100, imageUrl: getProductImage("Saw") },
  { id: generateId("Laser"), name: "Laser", price: 50, category: "Standard", rarity: "Godly", description: "High-tech laser godly gun.", inStock: 100, imageUrl: getProductImage("Laser") },
  { id: generateId("Heat"), name: "Heat", price: 55, category: "Standard", rarity: "Godly", description: "Fiery heat godly knife.", inStock: 100, imageUrl: getProductImage("Heat") },
  { id: generateId("Luger"), name: "Luger", price: 50, category: "Standard", rarity: "Godly", description: "Classic luger godly gun.", inStock: 100, imageUrl: getProductImage("Luger") },
  { id: generateId("Shark"), name: "Shark", price: 60, category: "Standard", rarity: "Godly", description: "Ocean shark-themed godly knife.", inStock: 100, imageUrl: getProductImage("Shark") },
  { id: generateId("Slasher"), name: "Slasher", price: 55, category: "Standard", rarity: "Godly", description: "Sharp slasher godly knife.", inStock: 100, imageUrl: getProductImage("Slasher") },
  { id: generateId("Pixel"), name: "Pixel", price: 45, category: "Standard", rarity: "Godly", description: "Retro pixel-art godly knife.", inStock: 100, imageUrl: getProductImage("Pixel") },
  { id: generateId("Virtual"), name: "Virtual", price: 50, category: "Standard", rarity: "Godly", description: "Digital virtual godly knife.", inStock: 100, imageUrl: getProductImage("Virtual") },
  
  { id: generateId("Corrupt"), name: "Corrupt", price: 150, category: "Godly", rarity: "Godly", description: "The legendary corrupt knife with dark powers.", inStock: 100, imageUrl: getProductImage("Corrupt") },
  { id: generateId("Lightbringer"), name: "Lightbringer", price: 120, category: "Godly", rarity: "Godly", description: "Radiant lightbringer sword.", inStock: 100, imageUrl: getProductImage("Lightbringer") },
  { id: generateId("Darkbringer"), name: "Darkbringer", price: 120, category: "Godly", rarity: "Godly", description: "Dark and menacing darkbringer sword.", inStock: 100, imageUrl: getProductImage("Darkbringer") },
  { id: generateId("Eternal"), name: "Eternal", price: 100, category: "Godly", rarity: "Godly", description: "Timeless eternal godly knife.", inStock: 100, imageUrl: getProductImage("Eternal") },
  { id: generateId("Eternal II"), name: "Eternal II", price: 110, category: "Godly", rarity: "Godly", description: "Enhanced eternal II godly knife.", inStock: 100, imageUrl: getProductImage("Eternal II") },
  { id: generateId("Eternal III"), name: "Eternal III", price: 120, category: "Godly", rarity: "Godly", description: "Ultimate eternal III godly knife.", inStock: 100, imageUrl: getProductImage("Eternal III") },
  { id: generateId("Eternal IV"), name: "Eternal IV", price: 130, category: "Godly", rarity: "Godly", description: "Final form eternal IV godly knife.", inStock: 100, imageUrl: getProductImage("Eternal IV") },
  { id: generateId("Gemstone"), name: "Gemstone", price: 90, category: "Godly", rarity: "Godly", description: "Precious gemstone godly knife.", inStock: 100, imageUrl: getProductImage("Gemstone") },
  { id: generateId("Heartblade"), name: "Heartblade", price: 95, category: "Godly", rarity: "Godly", description: "Valentine heartblade godly knife.", inStock: 100, imageUrl: getProductImage("Heartblade") },
  { id: generateId("Handsaw"), name: "Handsaw", price: 85, category: "Godly", rarity: "Godly", description: "Industrial handsaw godly knife.", inStock: 100, imageUrl: getProductImage("Handsaw") },
  
  { id: generateId("Icewing"), name: "Icewing", price: 200, category: "Ancient", rarity: "Ancient", description: "Legendary frozen icewing ancient.", inStock: 100, imageUrl: getProductImage("Icewing") },
  { id: generateId("Batwing"), name: "Batwing", price: 220, category: "Ancient", rarity: "Ancient", description: "Dark batwing ancient knife.", inStock: 100, imageUrl: getProductImage("Batwing") },
  { id: generateId("Hallowscythe"), name: "Hallowscythe", price: 250, category: "Ancient", rarity: "Ancient", description: "Spooky Halloween scythe ancient.", inStock: 100, imageUrl: getProductImage("Hallowscythe") },
  { id: generateId("Harvester"), name: "Harvester", price: 280, category: "Ancient", rarity: "Ancient", description: "Grim harvester ancient scythe.", inStock: 100, imageUrl: getProductImage("Harvester") },
  { id: generateId("Logchopper"), name: "Logchopper", price: 180, category: "Ancient", rarity: "Ancient", description: "Mighty logchopper ancient axe.", inStock: 100, imageUrl: getProductImage("Logchopper") },
  { id: generateId("Icepiercer"), name: "Icepiercer", price: 190, category: "Ancient", rarity: "Ancient", description: "Frozen icepiercer ancient.", inStock: 100, imageUrl: getProductImage("Icepiercer") },
  { id: generateId("Vampires Axe"), name: "Vampires Axe", price: 210, category: "Ancient", rarity: "Ancient", description: "Vampire-themed ancient axe.", inStock: 100, imageUrl: getProductImage("Vampires Axe") },
  { id: generateId("Celestial"), name: "Celestial", price: 240, category: "Ancient", rarity: "Ancient", description: "Cosmic celestial ancient.", inStock: 100, imageUrl: getProductImage("Celestial") },
  { id: generateId("Gingerscope"), name: "Gingerscope", price: 175, category: "Ancient", rarity: "Ancient", description: "Festive gingerscope ancient gun.", inStock: 100, imageUrl: getProductImage("Gingerscope") },
  
  { id: generateId("Eternal Set"), name: "Eternal Set", price: 350, category: "Bundles", rarity: "Godly", description: "Complete eternal knife collection.", inStock: 100, imageUrl: getProductImage("Eternal Set") },
  { id: generateId("Elderwood Set"), name: "Elderwood Set", price: 400, category: "Bundles", rarity: "Ancient", description: "Full elderwood weapon set.", inStock: 100, imageUrl: getProductImage("Elderwood Set") },
  { id: generateId("Hallow Set"), name: "Hallow Set", price: 450, category: "Bundles", rarity: "Ancient", description: "Complete Halloween set.", inStock: 100, imageUrl: getProductImage("Hallow Set") },
  { id: generateId("Candy Set"), name: "Candy Set", price: 180, category: "Bundles", rarity: "Godly", description: "Sweet candy weapon set.", inStock: 100, imageUrl: getProductImage("Candy Set") },
  { id: generateId("Borealis Set"), name: "Borealis Set", price: 200, category: "Bundles", rarity: "Godly", description: "Northern lights borealis set.", inStock: 100, imageUrl: getProductImage("Borealis Set") },
  
  { id: generateId("Chroma Seer"), name: "Chroma Seer", price: 300, category: "Royal", rarity: "Chroma", description: "Radiant chroma seer with shifting colors.", inStock: 100, imageUrl: getProductImage("Chroma Seer") },
  { id: generateId("Chroma Laser"), name: "Chroma Laser", price: 350, category: "Royal", rarity: "Chroma", description: "High-tech chroma laser gun.", inStock: 100, imageUrl: getProductImage("Chroma Laser") },
  { id: generateId("Chroma Heat"), name: "Chroma Heat", price: 380, category: "Royal", rarity: "Chroma", description: "Blazing chroma heat knife.", inStock: 100, imageUrl: getProductImage("Chroma Heat") },
  { id: generateId("Chroma Shark"), name: "Chroma Shark", price: 400, category: "Royal", rarity: "Chroma", description: "Ocean chroma shark knife.", inStock: 100, imageUrl: getProductImage("Chroma Shark") },
  { id: generateId("Chroma Luger"), name: "Chroma Luger", price: 360, category: "Royal", rarity: "Chroma", description: "Classic chroma luger gun.", inStock: 100, imageUrl: getProductImage("Chroma Luger") },
  { id: generateId("Chroma Gemstone"), name: "Chroma Gemstone", price: 420, category: "Royal", rarity: "Chroma", description: "Precious chroma gemstone knife.", inStock: 100, imageUrl: getProductImage("Chroma Gemstone") },
  { id: generateId("Chroma Lightbringer"), name: "Chroma Lightbringer", price: 500, category: "Royal", rarity: "Chroma", description: "Radiant chroma lightbringer sword.", inStock: 100, imageUrl: getProductImage("Chroma Lightbringer") },
  { id: generateId("Chroma Darkbringer"), name: "Chroma Darkbringer", price: 500, category: "Royal", rarity: "Chroma", description: "Dark chroma darkbringer sword.", inStock: 100, imageUrl: getProductImage("Chroma Darkbringer") },
  { id: generateId("Chroma Elderwood Blade"), name: "Chroma Elderwood Blade", price: 480, category: "Royal", rarity: "Chroma", description: "Ancient chroma elderwood blade.", inStock: 100, imageUrl: getProductImage("Chroma Elderwood Blade") },
  { id: generateId("Chroma Fire Pets Set"), name: "Chroma Fire Pets Set", price: 550, category: "Royal", rarity: "Chroma", description: "Complete chroma fire pets collection.", inStock: 100, imageUrl: getProductImage("Chroma Fire Pets Set") },
];
